name: Deploy Docsify v5+ (Pre-Built)

on:
  push:
    branches:
      - main  # Change this if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsify  # Folder where pre-built Docsify files are stored
          branch: gh-pages  # GitHub Pages branch
